//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string id { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string add1 { get; set; }
        public string add2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string phone { get; set; }
        public string deptcode { get; set; }
        public Nullable<System.DateTime> hiredate { get; set; }
        public string jobcode { get; set; }
        public string comment { get; set; }
    }
}
